// <auto-generated />
using System;
using ClassLibrary1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary1.Migrations
{
    [DbContext(typeof(AirConditionerShop2023DbContext))]
    [Migration("20240529033355_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary1.Models.AirConditioner", b =>
                {
                    b.Property<int>("AirConditionerId")
                        .HasColumnType("int");

                    b.Property<string>("AirConditionerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("DollarPrice")
                        .HasColumnType("float");

                    b.Property<string>("FeatureFunction")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SoundPressureLevel")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SupplierId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Warranty")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("AirConditionerId")
                        .HasName("PK__AirCondi__EE2EB739C63FB1A1");

                    b.HasIndex("SupplierId");

                    b.ToTable("AirConditioner", (string)null);
                });

            modelBuilder.Entity("ClassLibrary1.Models.StaffMember", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.HasKey("MemberId")
                        .HasName("PK__StaffMem__0CF04B3886BCD49E");

                    b.HasIndex(new[] { "EmailAddress" }, "UQ__StaffMem__49A14740C75E125A")
                        .IsUnique()
                        .HasFilter("[EmailAddress] IS NOT NULL");

                    b.ToTable("StaffMember", (string)null);
                });

            modelBuilder.Entity("ClassLibrary1.Models.SupplierCompany", b =>
                {
                    b.Property<string>("SupplierId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlaceOfOrigin")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("SupplierDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__4BE666B4D29D1BE3");

                    b.ToTable("SupplierCompany", (string)null);
                });

            modelBuilder.Entity("ClassLibrary1.Models.AirConditioner", b =>
                {
                    b.HasOne("ClassLibrary1.Models.SupplierCompany", "Supplier")
                        .WithMany("AirConditioners")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__AirCondit__Suppl__29572725");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ClassLibrary1.Models.SupplierCompany", b =>
                {
                    b.Navigation("AirConditioners");
                });
#pragma warning restore 612, 618
        }
    }
}
